- name: Update MJB Software
  remote_user: root
  hosts: 
    - store
    - buildservers
    - panel
    - certbot
  vars:
    ansible_ssh_common_args: -oControlMaster=auto -oControlPersist=60s -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no
  roles:
    - mjb-role-webapp

- name: Reload Panel Service
  remote_user: root
  hosts: panel
  vars:
    ansible_ssh_common_args: -oControlMaster=auto -oControlPersist=60s -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no
  tasks:
    - name: Restart mjb.panel
      service:
        name: mjb.panel
        state: restarted

- name: Reload Certbot Worker
  remote_user: root
  hosts: certbot
  vars:
    ansible_ssh_common_args: -oControlMaster=auto -oControlPersist=60s -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no
  tasks:
    - name: Restart mjb.certbot
      service:
        name: mjb.certbot
        state: restarted

- name: Reload Worker
  remote_user: root
  hosts: buildservers
  vars:
    ansible_ssh_common_args: -oControlMaster=auto -oControlPersist=60s -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no
  tasks:
    - name: Restart mjb.worker
      service:
        name: mjb.worker
        state: restarted
